%YAML:1.0
Table_Reference(cm):
   rows: 1
   cols: 3
   dt: d
   data: [92.995, 79.006, 85.1807]
Table_Reference_to_Edge(cm):
   rows: 1
   cols: 3
   dt:   d
   data: [0, 203, 0]
Table_RotationCenter(cm):
   rows: 1
   cols: 3
   dt:   d
   data: [113.424, 43.16411, 88.9577]
Table_Width(cm): 60
Table_Length(cm): 320
Table_Height_at_0(cm): 95
Table_TopMargin(cm): 20
Table_BotMargin(cm): 15
Mask_Rot(deg): 1
Mask_MaxRot(deg): 60
Mask_MinRot(deg): -60
Crop_Width(mm): 5000
Crop_Height(mm): 5000
PixelPerLength(px/mm): 0.1
