%YAML:1.0
World_Quaternion(x,y,z,w):
   rows: 1
   cols: 4
   dt: d
   data: [-0.949572, 0.0194867, 0.0184274, -0.3124]
World_Translation(cm): 
   rows: 1
   cols: 3
   dt: d
   data: [-25.3718, 11.8257, 62.8515]
VirtualCamera_Position(cm):
   rows: 1
   cols: 3
   dt: d
   data: [25, -5, 60]
Table_Position(mm):
   rows: 1
   cols: 3
   dt: d
   data: [-48,-113.282,443.362]
Table_RotationCenter(cm):
   rows: 1
   cols: 3
   dt:   d
   data: [25.5, -4, 0]
Table_Width(cm): 5.5
Table_Length(cm): 22.5
Table_Height(cm): 31
Table_TopMargin(cm): 5
Table_BotMargin(cm): 5
Mask_CropWidth(px): 500
Mask_CropHeight(px): 500
Mask_Rot(deg): 1
Mask_MaxRot(deg): 90
Mask_MinRot(deg): -90
PixelPerLength(px/mm): 1
