%YAML:1.0
Table_Reference(cm):
   rows: 1
   cols: 3
   dt: d
   data: [25, 20, 31]
Table_Reference_to_Position(cm):
   rows: 1
   cols: 3
   dt:   d
   data: [0, 0, 0]
Table_RotationCenter(cm):
   rows: 1
   cols: 3
   dt:   d
   data: [29, 11, 0]
Table_Width(cm): 5.5
Table_Length(cm): 22.5
Table_Height_at_0(cm): 31
Table_TopMargin(cm): 5
Table_BotMargin(cm): 5
Mask_Rot(deg): 1
Mask_MaxRot(deg): 90
Mask_MinRot(deg): -90
Crop_Width(mm): 500
Crop_Height(mm): 500
PixelPerLength(px/mm): 1
